language: "ruby"
cache: bundler
rvm:
  - 2.2.3
addons:
  postgresql: "9.3"
bundler_args: "--binstubs --without production"
before_script:
  - "bin/rake db:create"
  - "bin/rake db:migrate"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: false